# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1507/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1507/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matt/NDFEX

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matt/NDFEX

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1507/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1507/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matt/NDFEX/CMakeFiles /home/matt/NDFEX//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matt/NDFEX/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matching_engine

# Build rule for target.
matching_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matching_engine
.PHONY : matching_engine

# fast build rule for target.
matching_engine/fast:
	$(MAKE) $(MAKESILENT) -f matching_engine/CMakeFiles/matching_engine.dir/build.make matching_engine/CMakeFiles/matching_engine.dir/build
.PHONY : matching_engine/fast

#=============================================================================
# Target rules for targets named bot_runner

# Build rule for target.
bot_runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bot_runner
.PHONY : bot_runner

# fast build rule for target.
bot_runner/fast:
	$(MAKE) $(MAKESILENT) -f bots/CMakeFiles/bot_runner.dir/build.make bots/CMakeFiles/bot_runner.dir/build
.PHONY : bot_runner/fast

#=============================================================================
# Target rules for targets named stable_bot_runner

# Build rule for target.
stable_bot_runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stable_bot_runner
.PHONY : stable_bot_runner

# fast build rule for target.
stable_bot_runner/fast:
	$(MAKE) $(MAKESILENT) -f bots/CMakeFiles/stable_bot_runner.dir/build.make bots/CMakeFiles/stable_bot_runner.dir/build
.PHONY : stable_bot_runner/fast

#=============================================================================
# Target rules for targets named reject_bot

# Build rule for target.
reject_bot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reject_bot
.PHONY : reject_bot

# fast build rule for target.
reject_bot/fast:
	$(MAKE) $(MAKESILENT) -f bots/CMakeFiles/reject_bot.dir/build.make bots/CMakeFiles/reject_bot.dir/build
.PHONY : reject_bot/fast

#=============================================================================
# Target rules for targets named smarter_bots

# Build rule for target.
smarter_bots: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 smarter_bots
.PHONY : smarter_bots

# fast build rule for target.
smarter_bots/fast:
	$(MAKE) $(MAKESILENT) -f bots/CMakeFiles/smarter_bots.dir/build.make bots/CMakeFiles/smarter_bots.dir/build
.PHONY : smarter_bots/fast

#=============================================================================
# Target rules for targets named print_snapshots

# Build rule for target.
print_snapshots: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 print_snapshots
.PHONY : print_snapshots

# fast build rule for target.
print_snapshots/fast:
	$(MAKE) $(MAKESILENT) -f bots/CMakeFiles/print_snapshots.dir/build.make bots/CMakeFiles/print_snapshots.dir/build
.PHONY : print_snapshots/fast

#=============================================================================
# Target rules for targets named md_snapshots

# Build rule for target.
md_snapshots: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 md_snapshots
.PHONY : md_snapshots

# fast build rule for target.
md_snapshots/fast:
	$(MAKE) $(MAKESILENT) -f market_data/CMakeFiles/md_snapshots.dir/build.make market_data/CMakeFiles/md_snapshots.dir/build
.PHONY : md_snapshots/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bot_runner"
	@echo "... matching_engine"
	@echo "... md_snapshots"
	@echo "... print_snapshots"
	@echo "... reject_bot"
	@echo "... smarter_bots"
	@echo "... stable_bot_runner"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

